#Weapon Description
weapon: Ruger 10/22 Eisen
caliber: 0.22
caliberUnit: inch
click.x: 0
click.y: 0
click.Unit: inch
click.Distance: 25
click.DistanceUnit: m
goal.plate.time: 45
goal.speed.time: 49
goal.speed.first: 2.5
goal.speed.rings: 300
goal.precision: 200
fallscheibe.type: KK	

