#Weapon Description
weapon: Hämmerli XEsse Eisen
caliber: 0.22
caliberUnit: inch
click.x: 5
click.y: 10
click.Unit: mm
click.Distance: 25
click.DistanceUnit: m
goal.plate.time: 45
goal.speed.time: 60
goal.speed.first: 2.5
goal.speed.rings: 300
goal.precision: 200
fallscheibe.type: KK

