#Weapon Description
weapon: Xesse Airpistole
caliber: 4.5
caliberUnit: mm
click.x: 5
click.y: 10
click.Unit: mm
click.Distance: 25
click.DistanceUnit: m
goal.plate.time: 45
goal.speed.time: 120
goal.speed.first: 2.5
goal.speed.rings: 300
goal.precision: 200
fallscheibe.type: KK

