#Weapon Description
weapon: DAR15 - Zielfernrohr
caliber: 5.56
caliberUnit: mm
click.x: 1
click.y: 1
click.Unit: cm
click.Distance: 100
click.DistanceUnit: m
goal.plate.time: 45
goal.speed.time: 42
goal.speed.first: 2.5
goal.speed.rings: 300
goal.precision: 200
fallscheibe.type: KK	

